name: CI - Build & Security Scan
 
on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
 
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/my-node-app
  IMAGE_TAG: ${{ github.sha }}
 
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Run ESLint
        run: npm run lint || true # adapt to your script
      - name: Run tests
        run: npm test || true
      - name: Run npm audit
        run: npm audit --audit-level=moderate || true
 
  build-and-scan:
    needs: lint-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to registry (GHCR example)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image (BuildKit)
        run: |
          docker build --progress=plain --tag ${IMAGE_NAME}:${IMAGE_TAG} .
      - name: Run Trivy scan (fail on CRITICAL)
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
      - name: Push image (only if scans passed)
        run: docker push ${IMAGE_NAME}:${IMAGE_TAG}
 
